<?php
$automobili = [
  [
    'id' => 1,
    'marca' => "Audi",
    'prezzo' => 11500.00,
    'trazione' => null,
    'km' => 245055,
    'modello' => "A4 allroad",    
    'accessori' => "Alzacristalli, elettrici Bracciol, Climatizzator, Controllo automatico clima, Cruise Contro,  Sensore di pioggia,  Sensori di parcheggio assistito posteriori,  Specchietti laterali elettrici,  Start/Stop Automatico,  Volante in pelle",    
    'carburante' => "Diesel",    
    'trasmissione' => "manuale",
    'cilindrata' => 1968,
    'cavalli' => 177,
    'proprietari' => 3,
    'targa' => null,
    'colore' => "grigio",
    'immatricolazione' => 2012,
    'numero porte' => 5,
    'località' => "PD",
    'immagine' => "https://img2.stcrm.it/images/24165087/HOR_STD/1000x/audi-a4-allroad-2020-01.jpg",
  ],
  [
    'id' => 2,
    'marca' => "Tesla",
    'prezzo' => 43000.00,
    'trazione' => "posteriore",
    'km' => 125000,
    'modello' => "Model S",    
    'accessori' => "Alzacristalli elettrici Bracciol, Chiusura centralizzata senza chiave, Climatizzator, Controllo automatico clima, Cruise Contro, Parabrezza riscaldato,  Portellone posteriore elettrico,  Regolazione elettrica sedili,  Riscaldamento ausiliario,  Sedili riscaldati,  Sensore di luminosità,  Sensore di pioggia,  Sensori di parcheggio assistito posteriori,  Sistema di parcheggio automatico, Sospensioni pneumatiche,  Specchietti laterali elettrici,  Supporto lombare,  Telecamera per parcheggio assistito,  Vetri oscurati,  Volante in pelle,  Volante multifunzione",    
    'carburante' => "elettrica",    
    'trasmissione' => "automatico",
    'cilindrata' => 1968,
    'cavalli' => 378,
    'proprietari' => 2,
    'targa' => null,
    'colore' => "nero",
    'immatricolazione' => 2015,
    'porte' => 5,
    'località' => "UD",
    'immagine' => "https://statics.quattroruote.it/content/dam/quattroruote/it/news/nuovi-modelli/2020/09/23/tesla_model_s_plaid_prezzo_autonomia_prestazioni_uscita/gallery/rbig/2020-Tesla-Model-S-Plaid-05.jpg",
  ],
  [
    'id' => 3,
    'marca' => "Lamborghini",
    'prezzo' => 199900.00,
    'trazione' => null,
    'km' => 15000,
    'modello' => "Huracan",    
    'accessori' => null,    
    'carburante' => "benzina",    
    'trasmissione' => "automatico",
    'cilindrata' => 5204,
    'cavalli' => 579,
    'proprietari' => 1,
    'targa' => null,
    'colore' => "rosso",
    'immatricolazione' => 2018,
    'porte' => 2,
    'località' => "MI",
    'immagine' => "https://www.lamborghini.com/sites/it-en/files/DAM/lamborghini/share%20img/huracan-rwd-facebook-og.jpg",
  ],
  [
    'id' => 4,
    'marca' => "Fiat",
    'prezzo' => 3800.00,
    'trazione' => "anteriore",
    'km' => 245055,
    'modello' => "Panda",    
    'accessori' => "Alzacristalli elettrici Climatizzator,  Parabrezza riscaldato,  Sedile posteriore sdoppiato,  Supporto lombare",    
    'carburante' => "Metano",    
    'trasmissione' => "manuale",
    'cilindrata' => 1368,
    'cavalli' => 77,
    'proprietari' => 1,
    'targa' => null,
    'colore' => "rosso",
    'immatricolazione' => 2011,
    'porte' => 5,
    'località' => "RM",
    'immagine' => "https://img2.stcrm.it/images/24165087/HOR_STD/1000x/audi-a4-allroad-2020-01.jpg",
  ],
  [
    'id' => 5,
    'marca' => "Peugeot",
    'prezzo' => 11747.00,
    'trazione' => "anteriore",
    'km' => 98783,
    'modello' => "3008",    
    'accessori' => "Alzacristalli elettrici Bracciol, Climatizzator, Controllo automatico clima, Cruise Contro,  Sedile posteriore sdoppiato,  Sensori di luminosità,  Sensore di pioggia,  Sensori di parcheggio assistito posteriori,  Specchietti laterali elettrici,  Supporto lombare,",    
    'carburante' => "Diesel",    
    'trasmissione' => "manuale",
    'cilindrata' => 1560,
    'cavalli' => 116,
    'proprietari' => 2,
    'targa' => null,
    'colore' => "grigio",
    'immatricolazione' => 2014,
    'porte' => 5,
    'località' => "NA",
    'immagine' => "https://cdn.miacar.it/thumbs/vehicle-gallery-800x560/cars/PEUGEOT/3008/bluehdi-130-s-s-eat8-allure-pack/grigio-artense/6a0cea6/a-v6.jpeg",
  ],
]
?>